apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infra-automation
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  path: ./update
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
