---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: launchpad-charts
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-configs
    - name: cert-manager
    - name: postgres
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: apps
