---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: infra/monitoring/controllers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-controllers
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: infra/monitoring/configs
