---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  wait: true
  path: ./infra/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
