apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: graphops
spec:
  interval: 12h
  url: http://graphops.github.io/launchpad-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: graph-node
spec:
  interval: 1h
  chart:
    spec:
      version: "0.5.3"
      chart: graph-node
      sourceRef:
        kind: HelmRepository
        name: graphops
      interval: 12h
  install:
    crds: Create
    timeout: 9m
  upgrade:
    crds: CreateReplace
    timeout: 9m
  values:
    grafana:
      dashboards: true
    graphNodeDefaults:
      env:
        IPFS: "https://ipfs.network.thegraph.com"
        PRIMARY_SUBGRAPH_DATA_PGHOST: graph-rw
        PRIMARY_SUBGRAPH_DATA_PGDATABASE: graph
      secretEnv:
        PRIMARY_SUBGRAPH_DATA_PGUSER:
          secretName: postgres-config
          key: username
        PRIMARY_SUBGRAPH_DATA_PGPASSWORD:
          secretName: postgres-config
          key: password
    graphNodeGroups:
      combined:
        enabled: true
        replicaCount: 1
        includeInIndexPools:
          - default
        env:
          NODE_ROLE: combined-mode
    blockIngestorGroupName: combined
