---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: graph-node
spec:
  dependsOn:
    - name: graph-db
  interval: 5m
  retryInterval: 30s
  timeout: 4m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: apps/launchpad-charts/graph-node
